---
- name: Configurar servidor e fazer deploy
  hosts: app
  become: true

  tasks:
    - name: Atualiza pacotes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instala dependências para adicionar repositórios Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Adiciona a chave GPG do Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adiciona o repositório oficial do Docker
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
        update_cache: yes

    - name: Instala Docker e Docker Compose Plugin
      apt:
        name:
          - docker.io
          - docker-compose-plugin
        state: present

    - name: Clona seu repositório (exemplo)
      git:
        repo: https://github.com/Kript0n007/ansible.git
        dest: /opt/app
        version: gui

    - name: Verifica se site.html existe
      stat:
        path: /opt/app/sitezin/site.html
      register: site_file
      failed_when: not site_file.stat.exists or site_file.stat.isdir

    - name: Sobe aplicação com Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt/app
        state: present
      register: docker_compose_result
      failed_when: docker_compose_result.failed
