---
- name: Configurar servidor e fazer deploy
  hosts: app
  become: true

  tasks:
    - name: Atualiza pacotes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instala Docker e Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Clona seu repositório (exemplo)
      git:
        repo: https://github.com/Kript0n007/ansible.git
        dest: /opt/app
        version: gui

    - name: Verifica se site.html existe
      stat:
        path: /opt/app/site.html
      register: site_file
      failed_when: not site_file.stat.exists or site_file.stat.isdir

    - name: Sobe aplicação com Docker Compose
      community.docker.docker_compose:
        project_src: /opt/app
        state: present
      register: docker_compose_result
      failed_when: docker_compose_result.failed
